# Generated by Django 5.1.2 on 2024-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью блога",
                null=True,
                upload_to="blogs/photo",
                verbose_name="Превью",
            ),
        ),
    ]
