# Generated by Django 5.1.3 on 2024-12-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_blog_autor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="autor",
            new_name="creator",
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Введите имя автора",
                        max_length=50,
                        null=True,
                        verbose_name="Имя автора",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Введите фамилию автора",
                        max_length=50,
                        null=True,
                        verbose_name="Фамилия автора",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autor",
                        to="blogs.blog",
                        verbose_name="Автор статьи",
                    ),
                ),
            ],
        ),
    ]
