# Generated by Django 5.1.2 on 2024-12-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_rename_autor_blog_creator_autor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [("can_unpublish_blog", "can unpublish blog")],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
